server:
  port: 9094

spring:
  # mysql 配置
  datasource:
    url: jdbc:mysql://10.20.1.130:3306/agv?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xdcplus.com

  # redis 缓存配置
  redis:
    host: localhost
    port: 6379
    database: 0

#Swagger lock
swagger:
  enabled: true

netty:
  server:
    host: 127.0.0.1
    port: 8080









